### ISSUE TITLE
How to reproduce results on DNA dataset

### ISSUE THREAD

**Issue by cai-lw** [rdspring1/MISSION#2]
I can now run on other datasets, but the DNA dataset seems to have a very different format, and I can't infer the usage from the source code.

**Comment by rdspring1** [comment]
Did you download the dataset from [here](http://projects.cbio.mines-paristech.fr/largescalemetagenomics/)?

**Comment by cai-lw** [comment]
@rdspring1 Yes, I downloaded and installed as instructed, but then I have no idea how to use it with MISSION.

**Comment by rdspring1** [comment]
First, you will need to build _drawfrag_ and _fasta2vw_ in the **tools** directory. 

For training, you will run the **2-build-models/src/01.main.sh** script. The original script generates the training dataset in VW format from the metagenomic database and then pipes it directly into VW. You need to modify the script to save the dataset to a file, and then run Mission.

For testing, you need to run **1-generate-test-datasets/src/01.generate-dataset-fragments.sh** script. Then, you need to modify the **3-make-predictions/src/01.make-predictions.sh** to generate the VW test dataset.

**Comment by cai-lw** [comment]
Huge thanks! It's now working.

**Comment by cai-lw** [comment]
By the way, did you implement baseline approaches like Feature Hashing and Iterative Hard Threshold in this library? I saw some comments and variable names mentioning them but I am not sure whether they are truly implemented.

**Comment by rdspring1** [comment]
Mission is combination of Feature Hashing and IHT. For IHT, you would disable the count-sketch. For Feature Hashing, you would eliminate the top-k heap and flatten the count-sketch.
