### ISSUE TITLE
MMAP issue when running criteo_tb dataset

### ISSUE THREAD

**Issue by YeWenting** [rdspring1/MISSION#4]
I am running 2.7TB criteo_tb dataset. I set topK to 250000 and D (1 << 20) - 1, but when I run the program, it throws MMAP Failure in fast parser. But in my understanding, fast parser should only load 1 page at a time?

I print the errno. It's 9, which corresponds to "Bad file number".

**Comment by rdspring1** [comment]
Did you try the smaller criteo 25gb dataset? Same format, but smaller. I haven't seen this error before.

**Comment by YeWenting** [comment]
Thanks for your response! I found out the reason is I don't have permission for the training data.
