### ISSUE TITLE
Getting error "error: use of undeclared identifier 'aligned_alloc'" during make command

### ISSUE THREAD

**Issue by neerajsharma9195** [rdspring1/MISSION#5]
Hi,

I am trying to run the MISSION code on Mac OS. 
When I am building the executables using make file then I am getting this error:
MISSION/src/include/cms.h:58:25: error: use of undeclared identifier 'aligned_alloc'
                                                                data = (float*) aligned_alloc(32, sizeof(float)*SIZE);

I am using this CMakeLists.txt:
`cmake_minimum_required(VERSION 3.15)
project(mission)
set(CMAKE_CXX_STANDARD 11)
include_directories("/usr/local/include")
include_directories( "/usr/local/opt/llvm/include")
link_directories("/usr/local/lib" "/usr/local/opt/llvm/lib")
#add_executable(mission /Users/neerajsharma/my_work/umass/umass_study/1st_sem/CS689/MISSION/src/mission_logistic.cpp)
add_executable(mission /Users/neerajsharma/my_work/umass/umass_study/1st_sem/CS689/MISSION/src/mission_logistic.cpp /Users/neerajsharma/my_work/umass/umass_study/1st_sem/CS689/MISSION/src/fine_mission_softmax.cpp)
include_directories("/Users/neerajsharma/my_work/umass/umass_study/1st_sem/CS689/MISSION/src/include")`

I am using this cmake command:
cmake -D CMAKE_C_COMPILER=/usr/local/bin/gcc-9 -D CMAKE_CXX_COMPILER=/usr/bin/g++ .

@rdspring1  Can you please help me in solving this issue?

**Comment by rdspring1** [comment]
Can you compile the MISSION code with the original Makefile?
Just curious if you get the same error.

**Comment by neerajsharma9195** [comment]
Yes, I tried compiling with original Makefile:
When I tried first error I received was:
`fast_parser.cpp:31:66: error: use of undeclared identifier 'MAP_POPULATE'
                addr = mmap(NULL, pg_size, PROT_READ, MAP_FILE | MAP_PRIVATE | MAP_POPULATE, fd, offset);
                                                                               ^
1 error generated.
make: *** [fast_parser] Error 1
'''`

After that I removed MAP_POPULATE from fast_parser.cpp.

Then when I tried running make command, I received following error:
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'

In Mac, to run with fopenmp, I needed change g++ to gcc-9. So my MakeFile is looking like this:

`
all: clean softmax logistic

CFLAGS = -Wall --std=c++11 -O3 -Iinclude/

softmax: fast_parser murmurhash util
	gcc-9 $(CFLAGS) -fopenmp -pthread -mavx softmax.cpp fast_parser.o MurmurHash.o util.o -o softmax
	gcc-9 $(CFLAGS) -fopenmp -pthread -mavx coarse_mission_softmax.cpp fast_parser.o MurmurHash.o util.o -o coarse_mission_softmax
	gcc-9 $(CFLAGS) -fopenmp -pthread -mavx fine_mission_softmax.cpp fast_parser.o MurmurHash.o util.o -o fine_mission_softmax

logistic: fast_parser murmurhash util
	gcc-9$(CFLAGS) -fopenmp -pthread -mavx mission_logistic.cpp fast_parser.o MurmurHash.o util.o -o mission_logistic

parser: fast_parser murmurhash
	gcc-9 $(CFLAGS) -fopenmp -pthread parser_main.cpp fast_parser.o MurmurHash.o -o parser

fast_parser:
	gcc-9 $(CFLAGS) -o fast_parser.o -c fast_parser.cpp

murmurhash:
	gcc-9 $(CFLAGS) -o MurmurHash.o -c MurmurHash.cpp

util:
	gcc-9 $(CFLAGS) -mavx -o util.o -c util.cpp

clean:
	rm -rf MurmurHash.o
	rm -rf fast_parser.o
	rm -rf util.o
	rm -rf mission_logistic
	rm -rf fine_mission_softmax
	rm -rf coarse_mission_softmax
	rm -rf softmax
`

After this running make command giving this error:
`include/mem.h: In constructor 'MEM::MEM(unsigned int, unsigned int)':
include/mem.h:54:25: error: 'aligned_alloc' was not declared in this scope
   54 |         data = (float*) aligned_alloc(32, sizeof(float)*SIZE);
      |                         ^~~~~~~~~~~~~
make: *** [softmax] Error 1
`

So I searched for this error and its saying that aligned_alloc is supported in C11 not c++11.  Can you guide me, how to build it using original Makefile? 

Thanks

**Comment by rdspring1** [comment]
aligned_alloc is supported in c++17, so try the using the  `--std=c++17` flag.

I normally work with this code on ubuntu. aligned_alloc is a system function on linux, so it works with c++11. MAP_POPULATE flag is supported on linux.

**Comment by neerajsharma9195** [comment]
I have tried almost all things to run via --std=c++17 and still I am facing the same issue. 
`include/mem.h:54:25: error: use of undeclared identifier 'aligned_alloc'
                                                                data = (float*) aligned_alloc(32, sizeof(float)*SIZE)`

**Comment by rdspring1** [comment]
So you tried replacing `#include <stdlib.h>` with `#include <cstdlib>` and using `std::aligned_alloc` with the --std=c++17 flag?

The other alternative is to replace the `aligned_alloc` function with the standard `malloc` function, but you will likely lose the performance benefits of the SIMD AVX instructions.

This is a MacOS issue, so it is difficult for me to debug.

**Comment by neerajsharma9195** [comment]
Hi, So I removed aligned_alloc for now to run it. 

There are many posts where its written that it's not supported on OSX. Not sure why. 

Thanks.
